# Site settings
title: Parente Painting
email: parentepainting19@gmail.com
description: "Painting services provided in the greater Westchester Area."
baseurl: ""
url: "http://parentepainting.com"

sass:
  sass_dir: components

# Build settings
markdown: kramdown
permalink: pretty

# Collections
collections:
  projects:
    foo: bar
  reviews:
    foo: bar
